### ISSUE TITLE
Request update GLideN64 

### ISSUE THREAD

**Issue by andreluizmg** [tim241/BetterMajorasMaskInstaller#3]
Can you update the installers with the new GLideN64 Public Release 4.0

I tried it to make it work by my self but it didnt work with Majora-s-Mask-N64HD-Project  only with the Zelda Ocarina of time Community Retexture V7 texture

But your intaller works with Majora-s-Mask-N64HD-Project only the plugin is not up to date

**Comment by tim241** [comment]
my installer currently installs [this gliden64 version](https://github.com/gonetz/GLideN64/issues/2037#issuecomment-544322531), it's newer than the public release 4.0.

I'm also working on adding appveyor support to my installer to get the absolute latest builds.

**Comment by andreluizmg** [comment]
OK good to know this has the latest version
I was misinformed 
thanks
