### ISSUE TITLE
i cant find the game 

### ISSUE THREAD

**Issue by Fzde** [tim241/BetterMajorasMaskInstaller#4]
i installed it twice and both times the game didnt appear so i went on the internet to look for the rom and afterwards run it and it didnt look like the hd version at all pls help.

**Comment by tim241** [comment]
> I installed it twice and both times the game didn't appear

the installer doesn't install the game for you, otherwise it'd be breaking some laws which'd make this installer illegal.
> it didn't look like the HD version at all

that sounds odd, can you show me in a screenshot of the game and the GLideN64 texture tab(`options` -> `Configure Graphics Plugin...` -> `texture` tab)
