### ISSUE TITLE
no text and no menu

### ISSUE THREAD

**Issue by FrancoisFabre** [tim241/BetterMajorasMaskInstaller#5]
Hi,
when I use your installer I can't see the menu to choose a file. Also it seems that no text is appearing in dialogs. I haven't been further than the first minute but the problem disappears when I uncheck "use file storage instead of memory cache" except there's no hd texture.

I hope I can help you with this remark. I don't see how I did something wrong, I simply installed your installer and ran the ROM.

**Comment by tim241** [comment]
Can you show me a screenshot?

**Comment by FrancoisFabre** [comment]
Here are a picture of the menu and the first dialog of the game.

![Menu_MM](https://user-images.githubusercontent.com/47420983/79023276-29784680-7b80-11ea-9ecb-305718ceff25.PNG)
![text_MM](https://user-images.githubusercontent.com/47420983/79023277-2aa97380-7b80-11ea-8d5f-62cb417d53d0.PNG)

**Comment by GhostlyDark** [comment]
I can't reproduce this.

What are your system specifications including the graphics card?

**Comment by FrancoisFabre** [comment]
computer : MSI GP63 Leopard 8RE
OS : windows 10 family
Type : PC x64
Processor : Intel Core i5-8300H CPU @ 2.30GHz, 2301MHz, 4 cores, 8 logic processors
RAM : 8 Go
Graphics card : Intel UHD Graphics 630 and NVIDIA GeForce GTX 1060

Tell me if you need more informations.
