### ISSUE TITLE
Unknown memory action

### ISSUE THREAD

**Issue by carlcorder** [tim241/BetterMajorasMaskInstaller#7]
First, thank you so much for making this tool!

From what I can tell, the installation process went smoothly. It installed the latest version of Project64: 

![pic](https://i.ibb.co/Px4HHRt/p64.png)

I checked that plugins are present:

![pic](https://i.ibb.co/7rWQnD2/plugins.png)

along with the textures:

![pic](https://i.ibb.co/rGmTL19/textures.png)

But for some reason, I'm getting a "Unknown memory action error, Emulation stopped" shortly after I start the ROM:

![pic](https://i.ibb.co/gJfX2Qk/memory-error.png)

I've verified that the ROM does work without the plugins/textures. Any ideas on how I could troubleshoot what's going on?

**Comment by tim241** [comment]
Can you try options -> configure audio plugin -> changing the backend sound driver?

**Comment by carlcorder** [comment]
My options for the Backend Sound Driver are:

- DirectSound 8 Driver
- DirectSound 8 Legacy Driver
- No Sound Driver
- WASAPI Driver (experimental)
- WaveOut Driver
- XAudio2 Driver
- XAudio2 Legacy Driver

It was originally set to XAudio2, I noticed that the XAudio2 Legacy Driver also produced the "Unknown memory action" error. After testing them all I found the DirectSound8 and WASAPI drivers produce the best quality sound. However, the graphics are highly pixelated and I'm not sure if the textures are being properly applied:

![image](https://user-images.githubusercontent.com/6445816/86537230-0c1ef400-beb3-11ea-84f4-292de2db6894.png)

If you have any suggestions for how I can keep debugging I would greatly appreciate it!

**Comment by tim241** [comment]
that graphical corruption is caused by a bug in intel's gpu drivers, unfixable by me sadly, you can try

1) updating the Intel gpu drivers(I'm not sure if this fixes it)
2) buying/using a dedicated gpu(by amd/nvidia)

nothing I can do about that, I'm sorry.

**Comment by carlcorder** [comment]
No problem at all. I was able to figure out that it wasn't actually loading the texture pack correctly and had a suspicion that the issues weren't related to your installer in any way. Thanks so much with your help troubleshooting!
