### ISSUE TITLE
Screen looking corrupted/ super pixelated

### ISSUE THREAD

**Issue by venosif** [tim241/BetterMajorasMaskInstaller#8]
Used the auto installer. The game looks like this whenever I try to load it.
![1](https://user-images.githubusercontent.com/68295868/87458420-ce128600-c5be-11ea-8ba7-d56cb4c190eb.png)
![2](https://user-images.githubusercontent.com/68295868/87458422-ce128600-c5be-11ea-97cd-403676b2c129.png)
![3](https://user-images.githubusercontent.com/68295868/87458424-ceab1c80-c5be-11ea-8b43-5dd260f4c9e3.png)

**Comment by tim241** [comment]
Are you using an intel igpu? If so that's an intel gpu driver bug, unfixable by me.
